---
version: '3.6'
services:
  quadbot_ps: 
    container_name: quadbot_ps
    build: 
      context: ./ 
      args:
        PLATFORM: pokemon-showdown 
  quadbot_ds: 
    container_name: quadbot_ds
    build: 
      context: ./ 
      args:
        PLATFORM: discord 

  searx:
    container_name: searx 
    ports: ['8888:8888']
    build: searx/
  db:
    image: postgres 
    ports: ['5432:54232']
    
    volumes:
      - ./db/:/root/db/